// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file apponly.proto (package meshtastic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ChannelSettings } from "./channel_pb";
import { file_channel } from "./channel_pb";
import type { Config_LoRaConfig } from "./config_pb";
import { file_config } from "./config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apponly.proto.
 */
export const file_apponly: GenFile = /*@__PURE__*/
  fileDesc("Cg1hcHBvbmx5LnByb3RvEgptZXNodGFzdGljIm8KCkNoYW5uZWxTZXQSLQoIc2V0dGluZ3MYASADKAsyGy5tZXNodGFzdGljLkNoYW5uZWxTZXR0aW5ncxIyCgtsb3JhX2NvbmZpZxgCIAEoCzIdLm1lc2h0YXN0aWMuQ29uZmlnLkxvUmFDb25maWdCYgoTY29tLmdlZWtzdmlsbGUubWVzaEINQXBwT25seVByb3Rvc1oiZ2l0aHViLmNvbS9tZXNodGFzdGljL2dvL2dlbmVyYXRlZKoCFE1lc2h0YXN0aWMuUHJvdG9idWZzugIAYgZwcm90bzM", [file_channel, file_config]);

/**
 *
 * This is the most compact possible representation for a set of channels.
 * It includes only one PRIMARY channel (which must be first) and
 * any SECONDARY channels.
 * No DISABLED channels are included.
 * This abstraction is used only on the the 'app side' of the world (ie python, javascript and android etc) to show a group of Channels as a (long) URL
 *
 * @generated from message meshtastic.ChannelSet
 */
export type ChannelSet = Message<"meshtastic.ChannelSet"> & {
  /**
   *
   * Channel list with settings
   *
   * @generated from field: repeated meshtastic.ChannelSettings settings = 1;
   */
  settings: ChannelSettings[];

  /**
   *
   * LoRa config
   *
   * @generated from field: meshtastic.Config.LoRaConfig lora_config = 2;
   */
  loraConfig?: Config_LoRaConfig;
};

/**
 * Describes the message meshtastic.ChannelSet.
 * Use `create(ChannelSetSchema)` to create a new message.
 */
export const ChannelSetSchema: GenMessage<ChannelSet> = /*@__PURE__*/
  messageDesc(file_apponly, 0);

