// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file cannedmessages.proto (package meshtastic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cannedmessages.proto.
 */
export const file_cannedmessages: GenFile = /*@__PURE__*/
  fileDesc("ChRjYW5uZWRtZXNzYWdlcy5wcm90bxIKbWVzaHRhc3RpYyItChlDYW5uZWRNZXNzYWdlTW9kdWxlQ29uZmlnEhAKCG1lc3NhZ2VzGAEgASgJQm4KE2NvbS5nZWVrc3ZpbGxlLm1lc2hCGUNhbm5lZE1lc3NhZ2VDb25maWdQcm90b3NaImdpdGh1Yi5jb20vbWVzaHRhc3RpYy9nby9nZW5lcmF0ZWSqAhRNZXNodGFzdGljLlByb3RvYnVmc7oCAGIGcHJvdG8z");

/**
 *
 * Canned message module configuration.
 *
 * @generated from message meshtastic.CannedMessageModuleConfig
 */
export type CannedMessageModuleConfig = Message<"meshtastic.CannedMessageModuleConfig"> & {
  /**
   *
   * Predefined messages for canned message module separated by '|' characters.
   *
   * @generated from field: string messages = 1;
   */
  messages: string;
};

/**
 * Describes the message meshtastic.CannedMessageModuleConfig.
 * Use `create(CannedMessageModuleConfigSchema)` to create a new message.
 */
export const CannedMessageModuleConfigSchema: GenMessage<CannedMessageModuleConfig> = /*@__PURE__*/
  messageDesc(file_cannedmessages, 0);

