// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file clientonly.proto (package meshtastic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { LocalConfig, LocalModuleConfig } from "./localonly_pb";
import { file_localonly } from "./localonly_pb";
import type { Position } from "./mesh_pb";
import { file_mesh } from "./mesh_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file clientonly.proto.
 */
export const file_clientonly: GenFile = /*@__PURE__*/
  fileDesc("ChBjbGllbnRvbmx5LnByb3RvEgptZXNodGFzdGljIqkDCg1EZXZpY2VQcm9maWxlEhYKCWxvbmdfbmFtZRgBIAEoCUgAiAEBEhcKCnNob3J0X25hbWUYAiABKAlIAYgBARIYCgtjaGFubmVsX3VybBgDIAEoCUgCiAEBEiwKBmNvbmZpZxgEIAEoCzIXLm1lc2h0YXN0aWMuTG9jYWxDb25maWdIA4gBARI5Cg1tb2R1bGVfY29uZmlnGAUgASgLMh0ubWVzaHRhc3RpYy5Mb2NhbE1vZHVsZUNvbmZpZ0gEiAEBEjEKDmZpeGVkX3Bvc2l0aW9uGAYgASgLMhQubWVzaHRhc3RpYy5Qb3NpdGlvbkgFiAEBEhUKCHJpbmd0b25lGAcgASgJSAaIAQESHAoPY2FubmVkX21lc3NhZ2VzGAggASgJSAeIAQFCDAoKX2xvbmdfbmFtZUINCgtfc2hvcnRfbmFtZUIOCgxfY2hhbm5lbF91cmxCCQoHX2NvbmZpZ0IQCg5fbW9kdWxlX2NvbmZpZ0IRCg9fZml4ZWRfcG9zaXRpb25CCwoJX3Jpbmd0b25lQhIKEF9jYW5uZWRfbWVzc2FnZXNCZQoTY29tLmdlZWtzdmlsbGUubWVzaEIQQ2xpZW50T25seVByb3Rvc1oiZ2l0aHViLmNvbS9tZXNodGFzdGljL2dvL2dlbmVyYXRlZKoCFE1lc2h0YXN0aWMuUHJvdG9idWZzugIAYgZwcm90bzM", [file_localonly, file_mesh]);

/**
 *
 * This abstraction is used to contain any configuration for provisioning a node on any client.
 * It is useful for importing and exporting configurations.
 *
 * @generated from message meshtastic.DeviceProfile
 */
export type DeviceProfile = Message<"meshtastic.DeviceProfile"> & {
  /**
   *
   * Long name for the node
   *
   * @generated from field: optional string long_name = 1;
   */
  longName?: string;

  /**
   *
   * Short name of the node
   *
   * @generated from field: optional string short_name = 2;
   */
  shortName?: string;

  /**
   *
   * The url of the channels from our node
   *
   * @generated from field: optional string channel_url = 3;
   */
  channelUrl?: string;

  /**
   *
   * The Config of the node
   *
   * @generated from field: optional meshtastic.LocalConfig config = 4;
   */
  config?: LocalConfig;

  /**
   *
   * The ModuleConfig of the node
   *
   * @generated from field: optional meshtastic.LocalModuleConfig module_config = 5;
   */
  moduleConfig?: LocalModuleConfig;

  /**
   *
   * Fixed position data
   *
   * @generated from field: optional meshtastic.Position fixed_position = 6;
   */
  fixedPosition?: Position;

  /**
   *
   * Ringtone for ExternalNotification
   *
   * @generated from field: optional string ringtone = 7;
   */
  ringtone?: string;

  /**
   *
   * Predefined messages for CannedMessage
   *
   * @generated from field: optional string canned_messages = 8;
   */
  cannedMessages?: string;
};

/**
 * Describes the message meshtastic.DeviceProfile.
 * Use `create(DeviceProfileSchema)` to create a new message.
 */
export const DeviceProfileSchema: GenMessage<DeviceProfile> = /*@__PURE__*/
  messageDesc(file_clientonly, 0);

