// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file connection_status.proto (package meshtastic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file connection_status.proto.
 */
export const file_connection_status: GenFile = /*@__PURE__*/
  fileDesc("Chdjb25uZWN0aW9uX3N0YXR1cy5wcm90bxIKbWVzaHRhc3RpYyKxAgoWRGV2aWNlQ29ubmVjdGlvblN0YXR1cxIzCgR3aWZpGAEgASgLMiAubWVzaHRhc3RpYy5XaWZpQ29ubmVjdGlvblN0YXR1c0gAiAEBEjsKCGV0aGVybmV0GAIgASgLMiQubWVzaHRhc3RpYy5FdGhlcm5ldENvbm5lY3Rpb25TdGF0dXNIAYgBARI9CglibHVldG9vdGgYAyABKAsyJS5tZXNodGFzdGljLkJsdWV0b290aENvbm5lY3Rpb25TdGF0dXNIAogBARI3CgZzZXJpYWwYBCABKAsyIi5tZXNodGFzdGljLlNlcmlhbENvbm5lY3Rpb25TdGF0dXNIA4gBAUIHCgVfd2lmaUILCglfZXRoZXJuZXRCDAoKX2JsdWV0b290aEIJCgdfc2VyaWFsImcKFFdpZmlDb25uZWN0aW9uU3RhdHVzEjMKBnN0YXR1cxgBIAEoCzIjLm1lc2h0YXN0aWMuTmV0d29ya0Nvbm5lY3Rpb25TdGF0dXMSDAoEc3NpZBgCIAEoCRIMCgRyc3NpGAMgASgFIk8KGEV0aGVybmV0Q29ubmVjdGlvblN0YXR1cxIzCgZzdGF0dXMYASABKAsyIy5tZXNodGFzdGljLk5ldHdvcmtDb25uZWN0aW9uU3RhdHVzInsKF05ldHdvcmtDb25uZWN0aW9uU3RhdHVzEhIKCmlwX2FkZHJlc3MYASABKAcSFAoMaXNfY29ubmVjdGVkGAIgASgIEhkKEWlzX21xdHRfY29ubmVjdGVkGAMgASgIEhsKE2lzX3N5c2xvZ19jb25uZWN0ZWQYBCABKAgiTAoZQmx1ZXRvb3RoQ29ubmVjdGlvblN0YXR1cxILCgNwaW4YASABKA0SDAoEcnNzaRgCIAEoBRIUCgxpc19jb25uZWN0ZWQYAyABKAgiPAoWU2VyaWFsQ29ubmVjdGlvblN0YXR1cxIMCgRiYXVkGAEgASgNEhQKDGlzX2Nvbm5lY3RlZBgCIAEoCEJlChNjb20uZ2Vla3N2aWxsZS5tZXNoQhBDb25uU3RhdHVzUHJvdG9zWiJnaXRodWIuY29tL21lc2h0YXN0aWMvZ28vZ2VuZXJhdGVkqgIUTWVzaHRhc3RpYy5Qcm90b2J1ZnO6AgBiBnByb3RvMw");

/**
 * @generated from message meshtastic.DeviceConnectionStatus
 */
export type DeviceConnectionStatus = Message<"meshtastic.DeviceConnectionStatus"> & {
  /**
   *
   * WiFi Status
   *
   * @generated from field: optional meshtastic.WifiConnectionStatus wifi = 1;
   */
  wifi?: WifiConnectionStatus;

  /**
   *
   * WiFi Status
   *
   * @generated from field: optional meshtastic.EthernetConnectionStatus ethernet = 2;
   */
  ethernet?: EthernetConnectionStatus;

  /**
   *
   * Bluetooth Status
   *
   * @generated from field: optional meshtastic.BluetoothConnectionStatus bluetooth = 3;
   */
  bluetooth?: BluetoothConnectionStatus;

  /**
   *
   * Serial Status
   *
   * @generated from field: optional meshtastic.SerialConnectionStatus serial = 4;
   */
  serial?: SerialConnectionStatus;
};

/**
 * Describes the message meshtastic.DeviceConnectionStatus.
 * Use `create(DeviceConnectionStatusSchema)` to create a new message.
 */
export const DeviceConnectionStatusSchema: GenMessage<DeviceConnectionStatus> = /*@__PURE__*/
  messageDesc(file_connection_status, 0);

/**
 *
 * WiFi connection status
 *
 * @generated from message meshtastic.WifiConnectionStatus
 */
export type WifiConnectionStatus = Message<"meshtastic.WifiConnectionStatus"> & {
  /**
   *
   * Connection status
   *
   * @generated from field: meshtastic.NetworkConnectionStatus status = 1;
   */
  status?: NetworkConnectionStatus;

  /**
   *
   * WiFi access point SSID
   *
   * @generated from field: string ssid = 2;
   */
  ssid: string;

  /**
   *
   * RSSI of wireless connection
   *
   * @generated from field: int32 rssi = 3;
   */
  rssi: number;
};

/**
 * Describes the message meshtastic.WifiConnectionStatus.
 * Use `create(WifiConnectionStatusSchema)` to create a new message.
 */
export const WifiConnectionStatusSchema: GenMessage<WifiConnectionStatus> = /*@__PURE__*/
  messageDesc(file_connection_status, 1);

/**
 *
 * Ethernet connection status
 *
 * @generated from message meshtastic.EthernetConnectionStatus
 */
export type EthernetConnectionStatus = Message<"meshtastic.EthernetConnectionStatus"> & {
  /**
   *
   * Connection status
   *
   * @generated from field: meshtastic.NetworkConnectionStatus status = 1;
   */
  status?: NetworkConnectionStatus;
};

/**
 * Describes the message meshtastic.EthernetConnectionStatus.
 * Use `create(EthernetConnectionStatusSchema)` to create a new message.
 */
export const EthernetConnectionStatusSchema: GenMessage<EthernetConnectionStatus> = /*@__PURE__*/
  messageDesc(file_connection_status, 2);

/**
 *
 * Ethernet or WiFi connection status
 *
 * @generated from message meshtastic.NetworkConnectionStatus
 */
export type NetworkConnectionStatus = Message<"meshtastic.NetworkConnectionStatus"> & {
  /**
   *
   * IP address of device
   *
   * @generated from field: fixed32 ip_address = 1;
   */
  ipAddress: number;

  /**
   *
   * Whether the device has an active connection or not
   *
   * @generated from field: bool is_connected = 2;
   */
  isConnected: boolean;

  /**
   *
   * Whether the device has an active connection to an MQTT broker or not
   *
   * @generated from field: bool is_mqtt_connected = 3;
   */
  isMqttConnected: boolean;

  /**
   *
   * Whether the device is actively remote syslogging or not
   *
   * @generated from field: bool is_syslog_connected = 4;
   */
  isSyslogConnected: boolean;
};

/**
 * Describes the message meshtastic.NetworkConnectionStatus.
 * Use `create(NetworkConnectionStatusSchema)` to create a new message.
 */
export const NetworkConnectionStatusSchema: GenMessage<NetworkConnectionStatus> = /*@__PURE__*/
  messageDesc(file_connection_status, 3);

/**
 *
 * Bluetooth connection status
 *
 * @generated from message meshtastic.BluetoothConnectionStatus
 */
export type BluetoothConnectionStatus = Message<"meshtastic.BluetoothConnectionStatus"> & {
  /**
   *
   * The pairing PIN for bluetooth
   *
   * @generated from field: uint32 pin = 1;
   */
  pin: number;

  /**
   *
   * RSSI of bluetooth connection
   *
   * @generated from field: int32 rssi = 2;
   */
  rssi: number;

  /**
   *
   * Whether the device has an active connection or not
   *
   * @generated from field: bool is_connected = 3;
   */
  isConnected: boolean;
};

/**
 * Describes the message meshtastic.BluetoothConnectionStatus.
 * Use `create(BluetoothConnectionStatusSchema)` to create a new message.
 */
export const BluetoothConnectionStatusSchema: GenMessage<BluetoothConnectionStatus> = /*@__PURE__*/
  messageDesc(file_connection_status, 4);

/**
 *
 * Serial connection status
 *
 * @generated from message meshtastic.SerialConnectionStatus
 */
export type SerialConnectionStatus = Message<"meshtastic.SerialConnectionStatus"> & {
  /**
   *
   * Serial baud rate
   *
   * @generated from field: uint32 baud = 1;
   */
  baud: number;

  /**
   *
   * Whether the device has an active connection or not
   *
   * @generated from field: bool is_connected = 2;
   */
  isConnected: boolean;
};

/**
 * Describes the message meshtastic.SerialConnectionStatus.
 * Use `create(SerialConnectionStatusSchema)` to create a new message.
 */
export const SerialConnectionStatusSchema: GenMessage<SerialConnectionStatus> = /*@__PURE__*/
  messageDesc(file_connection_status, 5);

