// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file paxcount.proto (package meshtastic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file paxcount.proto.
 */
export const file_paxcount: GenFile = /*@__PURE__*/
  fileDesc("Cg5wYXhjb3VudC5wcm90bxIKbWVzaHRhc3RpYyI1CghQYXhjb3VudBIMCgR3aWZpGAEgASgNEgsKA2JsZRgCIAEoDRIOCgZ1cHRpbWUYAyABKA1CYwoTY29tLmdlZWtzdmlsbGUubWVzaEIOUGF4Y291bnRQcm90b3NaImdpdGh1Yi5jb20vbWVzaHRhc3RpYy9nby9nZW5lcmF0ZWSqAhRNZXNodGFzdGljLlByb3RvYnVmc7oCAGIGcHJvdG8z");

/**
 *
 * TODO: REPLACE
 *
 * @generated from message meshtastic.Paxcount
 */
export type Paxcount = Message<"meshtastic.Paxcount"> & {
  /**
   *
   * seen Wifi devices
   *
   * @generated from field: uint32 wifi = 1;
   */
  wifi: number;

  /**
   *
   * Seen BLE devices
   *
   * @generated from field: uint32 ble = 2;
   */
  ble: number;

  /**
   *
   * Uptime in seconds
   *
   * @generated from field: uint32 uptime = 3;
   */
  uptime: number;
};

/**
 * Describes the message meshtastic.Paxcount.
 * Use `create(PaxcountSchema)` to create a new message.
 */
export const PaxcountSchema: GenMessage<Paxcount> = /*@__PURE__*/
  messageDesc(file_paxcount, 0);

