// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file rtttl.proto (package meshtastic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rtttl.proto.
 */
export const file_rtttl: GenFile = /*@__PURE__*/
  fileDesc("CgtydHR0bC5wcm90bxIKbWVzaHRhc3RpYyIfCgtSVFRUTENvbmZpZxIQCghyaW5ndG9uZRgBIAEoCUJmChNjb20uZ2Vla3N2aWxsZS5tZXNoQhFSVFRUTENvbmZpZ1Byb3Rvc1oiZ2l0aHViLmNvbS9tZXNodGFzdGljL2dvL2dlbmVyYXRlZKoCFE1lc2h0YXN0aWMuUHJvdG9idWZzugIAYgZwcm90bzM");

/**
 *
 * Canned message module configuration.
 *
 * @generated from message meshtastic.RTTTLConfig
 */
export type RTTTLConfig = Message<"meshtastic.RTTTLConfig"> & {
  /**
   *
   * Ringtone for PWM Buzzer in RTTTL Format.
   *
   * @generated from field: string ringtone = 1;
   */
  ringtone: string;
};

/**
 * Describes the message meshtastic.RTTTLConfig.
 * Use `create(RTTTLConfigSchema)` to create a new message.
 */
export const RTTTLConfigSchema: GenMessage<RTTTLConfig> = /*@__PURE__*/
  messageDesc(file_rtttl, 0);

