// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file xmodem.proto (package meshtastic, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file xmodem.proto.
 */
export const file_xmodem: GenFile = /*@__PURE__*/
  fileDesc("Cgx4bW9kZW0ucHJvdG8SCm1lc2h0YXN0aWMitgEKBlhNb2RlbRIrCgdjb250cm9sGAEgASgOMhoubWVzaHRhc3RpYy5YTW9kZW0uQ29udHJvbBILCgNzZXEYAiABKA0SDQoFY3JjMTYYAyABKA0SDgoGYnVmZmVyGAQgASgMIlMKB0NvbnRyb2wSBwoDTlVMEAASBwoDU09IEAESBwoDU1RYEAISBwoDRU9UEAQSBwoDQUNLEAYSBwoDTkFLEBUSBwoDQ0FOEBgSCQoFQ1RSTFoQGkJhChNjb20uZ2Vla3N2aWxsZS5tZXNoQgxYbW9kZW1Qcm90b3NaImdpdGh1Yi5jb20vbWVzaHRhc3RpYy9nby9nZW5lcmF0ZWSqAhRNZXNodGFzdGljLlByb3RvYnVmc7oCAGIGcHJvdG8z");

/**
 * @generated from message meshtastic.XModem
 */
export type XModem = Message<"meshtastic.XModem"> & {
  /**
   * @generated from field: meshtastic.XModem.Control control = 1;
   */
  control: XModem_Control;

  /**
   * @generated from field: uint32 seq = 2;
   */
  seq: number;

  /**
   * @generated from field: uint32 crc16 = 3;
   */
  crc16: number;

  /**
   * @generated from field: bytes buffer = 4;
   */
  buffer: Uint8Array;
};

/**
 * Describes the message meshtastic.XModem.
 * Use `create(XModemSchema)` to create a new message.
 */
export const XModemSchema: GenMessage<XModem> = /*@__PURE__*/
  messageDesc(file_xmodem, 0);

/**
 * @generated from enum meshtastic.XModem.Control
 */
export enum XModem_Control {
  /**
   * @generated from enum value: NUL = 0;
   */
  NUL = 0,

  /**
   * @generated from enum value: SOH = 1;
   */
  SOH = 1,

  /**
   * @generated from enum value: STX = 2;
   */
  STX = 2,

  /**
   * @generated from enum value: EOT = 4;
   */
  EOT = 4,

  /**
   * @generated from enum value: ACK = 6;
   */
  ACK = 6,

  /**
   * @generated from enum value: NAK = 21;
   */
  NAK = 21,

  /**
   * @generated from enum value: CAN = 24;
   */
  CAN = 24,

  /**
   * @generated from enum value: CTRLZ = 26;
   */
  CTRLZ = 26,
}

/**
 * Describes the enum meshtastic.XModem.Control.
 */
export const XModem_ControlSchema: GenEnum<XModem_Control> = /*@__PURE__*/
  enumDesc(file_xmodem, 0, 0);

